# MLX最適化 Qwen2-VL-4B設定
dataset: techreport
split: test

preprocess:
  vision:
    enable: true
    model: Salesforce/blip-image-captioning-base
  chunker:
    method: page
    overlap: 0

agents:
  text:
    enable: true
    model: sentence-transformers/all-MiniLM-L6-v2
    index: indices/tech_text_mlx_qwen_faiss
    top_k: 20

  image:
    enable: true
    model: sentence-transformers/all-MiniLM-L6-v2
    index: indices/tech_img_mlx_qwen_faiss
    top_k: 20

decision:
  strategy: voting
  voting:
    method: rrf
    lambda: 20

generation:
  enable: true
  framework: mlx                  # MLX最適化フレームワーク使用
  model_type: qwen2-vl-4b        # MLX Qwen2-VL-4B-Instruct-4bit
  max_length: 300
  temperature: 0.7
  use_images: true

metrics: [recall@5, ndcg@5]
device: cpu                       # MLXは内部でApple Silicon最適化