# 最適化されたマルチモーダル設定
dataset: techreport
split: test

preprocess:
  vision:
    enable: true
    model: Salesforce/blip-image-captioning-base
  chunker:
    method: page
    overlap: 0

agents:
  text:
    enable: true
    model: sentence-transformers/all-MiniLM-L6-v2
    index: indices/tech_text_optimized_faiss
    top_k: 20                     # 最適化: 20

  image:
    enable: true
    model: sentence-transformers/all-MiniLM-L6-v2
    index: indices/tech_img_optimized_faiss
    top_k: 20                     # 最適化: 20

decision:
  strategy: voting
  voting:
    method: rrf
    lambda: 20                    # 最適化: 20 (デフォルト60から変更)

metrics: [recall@5, ndcg@5]
device: cpu                       # Apple Silicon MPS自動検出