# ext/configs/tech_min.yaml

dataset: techreport          # HF id を読む専用 adapter

split: test                  # REAL-MM-RAG のテスト split

preprocess:
  vision:                    # 画像→キャプション (あとで ON)
    enable: false
  chunker:
    method: page             # ページ丸ごと 1 チャンク
    overlap: 0

agents:
  text:                      # ★ TextRetrievalAgent
    enable: true
    model: BAAI/bge-m3
    index: indices/tech_text_faiss
    top_k: 80

  image:                     # ★ ImageRetrievalAgent (最初は OFF)
    enable: false
    model: Alibaba/Qwen-VL
    index: indices/tech_img_hnsw
    top_k: 40

decision:                    # ★ VotingDecisionAgent
  strategy: voting           # voting / expert_llm
  voting:
    method: rrf
    lambda: 60               # rank 補正ハイパラ

metrics: [recall@5, ndcg@5]  # bench/eval.py が計算
device: cuda:0               # CPU 開発なら "cpu"