# Phi-4-multimodal VLM設定
dataset: techreport
split: test

preprocess:
  vision:
    enable: true
    model: Salesforce/blip-image-captioning-base
  chunker:
    method: page
    overlap: 0

agents:
  text:
    enable: true
    model: sentence-transformers/all-MiniLM-L6-v2
    index: indices/tech_text_phi4_faiss
    top_k: 20

  image:
    enable: true
    model: sentence-transformers/all-MiniLM-L6-v2
    index: indices/tech_img_phi4_faiss
    top_k: 20

decision:
  strategy: voting
  voting:
    method: rrf
    lambda: 20

generation:
  enable: true
  model_type: phi4-multimodal     # Microsoft Phi-4-multimodal
  max_length: 200
  temperature: 0.6
  use_images: true

metrics: [recall@5, ndcg@5]
device: cpu